# Copyright (c) 2022 Jaehong Kang
# Licensed under Apache License v2.0

name: 'GitHub Actions for SwiftLint'
description: 'A tool to enforce Swift style and conventions'
author: 'Mert Karabulut <karabulutmert90@gmail.com>'
branding:
  icon: 'shield'
  color: 'orange'
inputs:
  swiftlint-args:
    description: "Arguments to SwiftLint."
    required: false
  working-directory:
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: swiftlint run
      run: |
        ${{ github.action_path }}/swiftlint.sh ${{ inputs.swiftlint-args }}
      shell: bash
      working-directory: '${{ github.workspace }}/${{ inputs.working-directory }}'
 
